# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import sys
import platform
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint,
                            QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence,
                           QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 600)
        MainWindow.setMinimumSize(QtCore.QSize(880, 600))

        #MainWindow.setWindowOpacity(0.95)

        MainWindow.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
                                 " QScrollBar:vertical {\n"
                                 "    border: none;\n"
                                 "    width: 10px;\n"
                                 " }\n"
                                 "\n"
                                 "/*  HANDLE BAR VERTICAL */\n"
                                 "QScrollBar::handle:vertical {    \n"
                                 "    background-color: rgb(120, 120, 120);\n"
                                 "    min-height: 30px;\n"
                                 "    border-radius: 5px;\n"
                                 "}\n"
                                 "QScrollBar::handle:vertical:hover{    \n"
                                 "    background-color: rgb(100, 100, 100);\n"
                                 "}\n"
                                 "QScrollBar::handle:vertical:pressed {    \n"
                                 "    background-color: rgb(80, 80, 80);\n"
                                 "}\n"
                                 "\n"
                                 "/* BTN TOP - SCROLLBAR */\n"
                                 "QScrollBar::sub-line:vertical {\n"
                                 "    border: none;\n"
                                 "    height: 1px;\n"
                                 "}\n"
                                 "\n"
                                 "/*QScrollBar::sub-line:vertical:hover {    \n"
                                 "    background-color: rgb(255, 0, 127);\n"
                                 "}\n"
                                 "QScrollBar::sub-line:vertical:pressed {    \n"
                                 "    background-color: rgb(185, 0, 92);\n"
                                 "}*/\n"
                                 "\n"
                                 "/* BTN BOTTOM - SCROLLBAR */\n"
                                 "QScrollBar::add-line:vertical {\n"
                                 "    border: none;\n"
                                 "    height: 15px;\n"
                                 "}\n"
                                 "\n"
                                 "/*QScrollBar::add-line:vertical:hover {    \n"
                                 "    background-color: rgb(255, 0, 127);\n"
                                 "}\n"
                                 "QScrollBar::add-line:vertical:pressed {    \n"
                                 "    background-color: rgb(185, 0, 92);\n"
                                 "}*/\n"
                                 "\n"
                                 "/* RESET ARROW */\n"
                                 "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
                                 "    background: none;\n"
                                 "}\n"
                                 "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                 "    background: none;\n"
                                 "}\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setStyleSheet("background-color: rgb(31, 31, 31);")
        self.background.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.background)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titlebar = QtWidgets.QFrame(self.background)
        self.titlebar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titlebar.setStyleSheet("background-color: none;")
        self.titlebar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titlebar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.titlebar)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(15, 8, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: white;\n"
                                       "font: 9pt \"Segoe UI\";")
        self.label_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.btns = QtWidgets.QFrame(self.titlebar)
        self.btns.setMaximumSize(QtCore.QSize(200, 150))
        self.btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btns.setObjectName("btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.btns)
        self.horizontalLayout_3.setContentsMargins(34, 0, 0, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimize = QtWidgets.QPushButton(self.btns)
        self.minimize.setMinimumSize(QtCore.QSize(55, 40))
        self.minimize.setMaximumSize(QtCore.QSize(55, 40))
        self.minimize.setToolTip("")
        self.minimize.setStyleSheet("QPushButton {\n"
                                    "background-color: none;\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "font: 8pt \"Segoe UI\";\n"
                                    "border: none;\n"
                                    "padding-bottom: 5px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover \n"
                                    "{ \n"
                                    "background-color: rgb(55, 55, 55);\n"
                                    "}\n"
                                    "")
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_3.addWidget(self.minimize)
        self.maximize = QtWidgets.QPushButton(self.btns)
        self.maximize.setMinimumSize(QtCore.QSize(55, 40))
        self.maximize.setMaximumSize(QtCore.QSize(55, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.maximize.setFont(font)
        self.maximize.setToolTip("")
        self.maximize.setStyleSheet("QPushButton {\n"
                                    "background-color: none;\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "font: 16pt \"Segoe UI\";\n"
                                    "border: none;\n"
                                    "padding-bottom: 12px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover \n"
                                    "{ \n"
                                    "background-color: rgb(55, 55, 55);\n"
                                    "}\n"
                                    "")
        self.maximize.setObjectName("maximize")
        self.horizontalLayout_3.addWidget(self.maximize)
        self.close = QtWidgets.QPushButton(self.btns)
        self.close.setMinimumSize(QtCore.QSize(55, 40))
        self.close.setMaximumSize(QtCore.QSize(55, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.close.setFont(font)
        self.close.setToolTip("")
        self.close.setStyleSheet("QPushButton {\n"
                                 "background-color: none;\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "font: 16pt \"Segoe UI\";\n"
                                 "\n"
                                 "border: none;\n"
                                 "padding-bottom: 7px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover \n"
                                 "{ \n"
                                 "\n"
                                 "    background-color: rgb(232, 17, 35);\n"
                                 "}\n"
                                 "")
        self.close.setObjectName("close")
        self.horizontalLayout_3.addWidget(self.close)
        self.horizontalLayout.addWidget(self.btns)
        self.verticalLayout.addWidget(self.titlebar)
        self.frame = QtWidgets.QFrame(self.background)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(450, 40))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open = QtWidgets.QPushButton(self.frame)
        self.open.setEnabled(True)
        self.open.setMinimumSize(QtCore.QSize(0, 30))
        self.open.setMaximumSize(QtCore.QSize(16777215, 30))
        self.open.setStyleSheet("QPushButton {\n"
                                "background-color: none;\n"
                                "color: rgb(255, 255, 255);\n"
                                "font: 14pt \"Segoe UI\";\n"
                                "border: none;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover \n"
                                "{ \n"
                                "border-bottom: 3px solid rgb(63, 63, 63, 0%);\n"
                                "}\n"
                                "")
        self.open.setCheckable(False)
        self.open.setObjectName("open")
        self.horizontalLayout_4.addWidget(self.open)
        self.save = QtWidgets.QPushButton(self.frame)
        self.save.setMinimumSize(QtCore.QSize(0, 30))
        self.save.setMaximumSize(QtCore.QSize(16777215, 30))
        self.save.setStyleSheet("QPushButton {\n"
                                "background-color: none;\n"
                                "color: rgb(255, 255, 255);\n"
                                "font: 14pt \"Segoe UI\";\n"
                                "border: none;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover \n"
                                "{ \n"
                                "border-bottom: 3px solid rgb(63, 63, 63, 0%);\n"
                                "}")
        self.save.setObjectName("save")
        self.horizontalLayout_4.addWidget(self.save)
        self.print = QtWidgets.QPushButton(self.frame)
        self.print.setMinimumSize(QtCore.QSize(0, 30))
        self.print.setMaximumSize(QtCore.QSize(16777215, 30))
        self.print.setStyleSheet("QPushButton {\n"
                                 "background-color: none;\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "font: 14pt \"Segoe UI\";\n"
                                 "border: none;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover \n"
                                 "{ \n"
                                 "border-bottom: 3px solid rgb(63, 63, 63, 0%);\n"
                                 "}\n"
                                 "")
        self.print.setObjectName("print")
        self.horizontalLayout_4.addWidget(self.print)
        self.view = QtWidgets.QPushButton(self.frame)
        self.view.setMinimumSize(QtCore.QSize(0, 30))
        self.view.setMaximumSize(QtCore.QSize(16777215, 30))
        self.view.setStyleSheet("QPushButton {\n"
                                "background-color: none;\n"
                                "color: rgb(255, 255, 255);\n"
                                "font: 14pt \"Segoe UI\";\n"
                                "border: none;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover \n"
                                "{ \n"
                                "border-bottom: 3px solid rgb(63, 63, 63, 0%);\n"
                                "}\n"
                                "")
        self.view.setObjectName("view")
        self.horizontalLayout_4.addWidget(self.view)
        self.help = QtWidgets.QPushButton(self.frame)
        self.help.setMinimumSize(QtCore.QSize(0, 30))
        self.help.setMaximumSize(QtCore.QSize(16777215, 30))
        self.help.setStyleSheet("QPushButton {\n"
                                "background-color: none;\n"
                                "color: rgb(255, 255, 255);\n"
                                "font: 14pt \"Segoe UI\";\n"
                                "border: none;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover \n"
                                "{ \n"
                                "border-bottom: 3px solid rgb(63, 63, 63, 0%);\n"
                                "}\n"
                                "")
        self.help.setObjectName("help")
        self.horizontalLayout_4.addWidget(self.help)
        self.verticalLayout.addWidget(self.frame)
        self.content_bar = QtWidgets.QFrame(self.background)
        self.content_bar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.content_bar.setStyleSheet("background-color: rgb(31, 31, 31);")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_bar)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.content_bar)
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("border: none;\n"
                                      "background: rgb(50, 50, 50);\n"
                                      "border-radius: 5px;\n"
                                      "color: white;")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContent = QtWidgets.QWidget()
        self.scrollAreaWidgetContent.setGeometry(QtCore.QRect(0, 0, 856, 496))
        self.scrollAreaWidgetContent.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContent.setObjectName("scrollAreaWidgetContent")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContent)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textArea = QtWidgets.QTextEdit(self.scrollAreaWidgetContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textArea.setFont(font)
        self.textArea.setStyleSheet("")
        self.textArea.setObjectName("textArea")
        self.horizontalLayout_2.addWidget(self.textArea)
        self.scrollArea.setWidget(self.scrollAreaWidgetContent)
        self.horizontalLayout_6.addWidget(self.scrollArea)
        self.verticalLayout_4.addWidget(self.widget)
        self.verticalLayout.addWidget(self.content_bar)
        self.horizontalLayout_5.addWidget(self.background)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionhgjgjhj = QtWidgets.QAction(MainWindow)
        self.actionhgjgjhj.setObjectName("actionhgjgjhj")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Notepad"))
        self.minimize.setText(_translate("MainWindow", "—"))
        self.maximize.setText(_translate("MainWindow", "□"))
        self.close.setText(_translate("MainWindow", "×"))
        self.open.setText(_translate("MainWindow", "Open"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.print.setText(_translate("MainWindow", "Print"))
        self.view.setText(_translate("MainWindow", "View"))
        self.help.setText(_translate("MainWindow", "Help"))
        self.actionhgjgjhj.setText(_translate("MainWindow", "hgjgjhj"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
